# [START app_yaml]
runtime: nodejs
env: flex
env_variables:
  SQL_USER: admin
  SQL_PASSWORD: ptiptr2019
  SQL_DATABASE: chronosdb
  INSTANCE_CONNECTION_NAME: chronos-234322:europe-west3:chronos-instance
beta_settings:
  cloud_sql_instances: chronos-234322:europe-west3:chronos-instance

handlers:
- url: /.*
  script: true
  secure: always
  redirect_http_response_code: 301
